### ISSUE TITLE
Why do I still have access to this repo?

### ISSUE THREAD

**Issue by cauli** [vtex/admin-promotions#137]
I miss you all but not that much 😄 

Hugs to you all, and to Bezão.

**Comment by cauli** [comment]
Wait, did you open source it?

**Comment by ericreis** [comment]
Because we love you @cauli! Also, because it's now open source!!!

![image](https://user-images.githubusercontent.com/5971264/67879591-00a54d00-fb1c-11e9-8555-4b80f7e7ef1a.png)

**Comment by cauli** [comment]
:not-bad:

**Comment by ericreis** [comment]
Also, why not that much?

**Comment by cauli** [comment]
Not enough to contribute to the project/review PRs 😆

**Comment by ohmyguigs** [comment]
@cauli  we miss you, pastel ❤️
